# Generated by Django 5.0.3 on 2024-04-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_administrator_book_bookauthors_user_event_floor_and_more'),
    ]

    operations = [

    ]