# Generated by Django 5.0.3 on 2024-04-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_password_field'),
    ]

    operations = [

    ]
