# Generated by Django 5.0.3 on 2024-04-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_passwords'),
    ]

    operations = [
    ]
