# Generated by Django 5.0.3 on 2024-04-11 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_password_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='User',
            name='user_password',
            field=models.CharField(db_column='User_password', max_length=128),
        ),
        migrations.AddField(
            model_name='Administrator',
            name='administrator_password',
            field=models.CharField(db_column='Administrator_password', max_length=128),
        ),
    ]
