# Generated by Django 5.0.3 on 2024-04-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20240411_0353'),
        ('api', '0008_auto_20240411_0401'),
    ]

    operations = [
    ]
