# Generated by Django 5.0.3 on 2024-04-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_merge_0007_auto_20240411_0353_0008_auto_20240411_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='User',
            name='User_password',
            field=models.CharField(db_column='User_password', max_length=128),
        ),
        migrations.AddField(
            model_name='Administrator',
            name='Administrator_password',
            field=models.CharField(db_column='Administrator_password', max_length=128),
        ),
    ]
