# Generated by Django 5.0.3 on 2024-04-11 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20240411_0406'),
    ]

    operations = [
    ]
