# Generated by Django 5.0.3 on 2024-04-11 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20240411_0414'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='penis_number',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
