# Generated by Django 5.0.3 on 2024-04-12 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.CharField(db_column='User_password', max_length=255),
        ),
    ]
