# Generated by Django 5.0.3 on 2024-04-12 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_user_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_password',
            new_name='User_password',
        ),
    ]
