# Generated by Django 5.0.3 on 2024-04-12 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_user_password_user_user_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'managed': True},
        ),
    ]
