# Generated by Django 5.0.3 on 2024-04-12 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_administrator_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seat',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='administrator',
            old_name='administrator_password',
            new_name='Administrator_password',
        ),
    ]
