# Generated by Django 5.0.3 on 2024-04-12 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_seat_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='floorno',
            field=models.ForeignKey(db_column='FloorNo', on_delete=django.db.models.deletion.DO_NOTHING, to='api.floor'),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_num',
            field=models.IntegerField(db_column='Seat_num', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seat',
            name='type',
            field=models.CharField(choices=[('Large', 'Large'), ('Medium', 'Medium'), ('Small', 'Small')], db_column='Type', max_length=255),
        ),
    ]
