# Generated by Django 5.0.3 on 2024-04-12 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_seatbook_options'),
    ]

    operations = [
    ]
