# Generated by Django 5.0.3 on 2024-04-12 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_seatbook_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='seatbook',
            name='seat_num',
            field=models.OneToOneField(db_column='Seat_num', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.seat'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='seatbook',
            unique_together={('user', 'seat_num')},
        ),
    ]
