# Generated by Django 5.0.3 on 2024-04-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_seatbook_seat_num_alter_seatbook_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatbook',
            name='time',
            field=models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], db_column='Time', max_length=255),
        ),
    ]
