# Generated by Django 5.0.3 on 2024-04-13 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_uploadimage_alter_seat_type'),
    ]

    operations = [
    ]
