# Generated by Django 5.0.3 on 2024-04-13 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20240413_0013'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyroom',
            options={'managed': True},
        ),
    ]
