# Generated by Django 5.0.3 on 2024-04-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_studyroom_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyroom',
            old_name='floor_no',
            new_name='floorno',
        ),
        migrations.AlterField(
            model_name='studyroom',
            name='hastv',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], db_column='HasTv', max_length=255),
        ),
    ]
