# Generated by Django 5.0.3 on 2024-04-13 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_studyroom_floorno_alter_studyroom_room_id'),
    ]

    operations = [ 
        migrations.RenameField(
            model_name='seatbook',
            old_name='user',
            new_name='user_id',
        ),
    ]
