# Generated by Django 5.0.3 on 2024-04-13 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_rename_seat_num_seatbook_seat_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyroombook',
            options={'managed': True},
        ),
    ]
