# Generated by Django 5.0.3 on 2024-04-13 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_studyroombook_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyroombook',
            name='time',
            field=models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], db_column='Time', max_length=255),
        ),
    ]
