# Generated by Django 5.0.3 on 2024-04-13 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_studyroombook_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyroombook',
            name='study_room',  # Changed field name from 'room' to 'study_room'
            field=models.OneToOneField(db_column='Room_ID2', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.studyroom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studyroombook',
            name='time',
            field=models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], db_column='Time', max_length=255),
        ),
    ]
