# Generated by Django 5.0.3 on 2024-04-13 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_studyroombook_room_alter_studyroombook_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studyroombook',
            old_name='study_room',
            new_name='room',
        ),
    ]
