# Generated by Django 5.0.3 on 2024-04-13 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_rename_study_room_studyroombook_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyroombook',
            name='room',
            field=models.OneToOneField(db_column='Room_ID', default=3, on_delete=django.db.models.deletion.DO_NOTHING, to='api.studyroom'),
        ),
    ]
