# Generated by Django 5.0.3 on 2024-04-13 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_studyroombook_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seatbook',
            options={'managed': False},
        ),
    ]
