# Generated by Django 5.0.3 on 2024-04-13 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_seatbook_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookrent',
            options={'managed': True},
        ),
    ]
