# Generated by Django 5.0.3 on 2024-04-13 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_bookrent_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrent',
            name='book',
            field=models.OneToOneField(db_column='Book_ID2', default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.book'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookrent',
            name='time',
            field=models.CharField(db_column='Lending_Time', default=1, max_length=255),
            preserve_default=False,
        ),
    ]
