# Generated by Django 5.0.3 on 2024-04-13 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_bookrent_lending_time_bookrent_book_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='bookrent',
            name='book',
            field=models.OneToOneField(db_column='Book_2ID', on_delete=django.db.models.deletion.DO_NOTHING, to='api.book'),
        ),
    ]
